- name: container_attach
  desc: choose a running container and attach to it
  alias: docker attach {{ container }}

- name: container_stop
  desc: choose a running container and stop it
  alias: docker stop {{ container }}

- name: container_start
  desc: choose a stopped container and start it
  alias: docker start {{ container_exited }}


- name: container_shell
  desc: Choose a running container and starts a shell
  alias: docker exec -it {{ container }} /bin/sh

- name: container_inspect
  desc: Choose a running container and run's docker inspect on it
  alias: docker inspect {{ container }}

- name: container_ip
  desc: Choose a running container and get it's IPAddress
  alias: echo {{ container_ip }}

- name: container_metrics
  desc: Choose a running container and get the app metrics
  alias: curl http://{{container_ip}}:{{ container_port }}/{{metrics_endpoint}}

- name: containers_del_stopped
  desc: Delete all stopped containers
  alias: docker ps -q --filter status=exited|xargs docker rm

